"detect file type
filetype plugin on
filetype indent on " load filetype-specific indent files

set number " show line numbers

"keypad on - must go before syntax enable 
set term=ansi 

set encoding=utf8

"setting tabs = 4 spaces
set expandtab " tabs are spaces
set smarttab
set tabstop=4 " number of visual spaces per tab
set shiftwidth=4
set softtabstop=4 " number of spaces in tab when editing
set autoindent

"search options
set hlsearch " highlight matches
set smartcase

"handle 80 character limit
"highlights text past 80 chars -- python only
"autocmd FileType python highlight OverLength ctermbg=red ctermfg=white guibg=#592929
"autocmd FileType python match OverLength /\%80v.\+/
"auto line break at 80 characters"
"set lbr
"set tw=80
"toggle vertical line at 80 chars
"set cc=80

"cursor column color set
highlight CursorLine ctermbg=none cterm=underline
set cursorline " highlight current line

"status line - {relative file path}/{file name} percentage
set ruler " show current col, row
"hi StatusLine term=none ctermfg=8 ctermbg=7
set statusline=%f\ %p
set laststatus=2

set paste

"clears terminal after exiting vim
set term=rxvt

"colors on
syntax enable " enable syntax processing
set t_Co=256
colorscheme elflord
set showcmd " show command in bottom bar
set wildmenu " visual autocomplete for cmd menu
set lazyredraw " redraw only when needed
set showmatch " highlight matching [{()}]
